SETR - Assignment 3: io.c File Reference
io.c File Reference
#include <zephyr/device.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>
#include "io.h"
#include "rtdb.h"
Macros
#define BTN0_NODE DT_ALIAS(sw0)
#define BTN1_NODE DT_ALIAS(sw1)
#define BTN2_NODE DT_ALIAS(sw2)
#define BTN3_NODE DT_ALIAS(sw3)
#define LED0_NODE DT_ALIAS(led0)
#define LED1_NODE DT_ALIAS(led1)
#define LED2_NODE DT_ALIAS(led2)
#define LED3_NODE DT_ALIAS(led3)
Functions
void io_set_led (int id, int state)
Sets the state of a specific LED.
void io_blink_led (int id)
Toggles the state of a specific LED.
void button_pressed (const struct device *dev, struct gpio_callback *cb, uint32_t pins)
void io_init (void)
Initializes all LED and button GPIOs.
Variables
static const struct gpio_dt_spec leds []
static const struct gpio_dt_spec buttons []
bool setpoint_defined
bool max_temp_defined
int temp_setpoint_buffer
int temp_max_buffer
bool uart_mode
static struct gpio_callback btn_cb_data [4]
Macro Definition Documentation
BTN0_NODE
#define BTN0_NODE DT_ALIAS(sw0)
Definition at line 8 of file io.c.
BTN1_NODE
#define BTN1_NODE DT_ALIAS(sw1)
Definition at line 9 of file io.c.
BTN2_NODE
#define BTN2_NODE DT_ALIAS(sw2)
Definition at line 10 of file io.c.
BTN3_NODE
#define BTN3_NODE DT_ALIAS(sw3)
Definition at line 11 of file io.c.
LED0_NODE
#define LED0_NODE DT_ALIAS(led0)
Definition at line 13 of file io.c.
LED1_NODE
#define LED1_NODE DT_ALIAS(led1)
Definition at line 14 of file io.c.
LED2_NODE
#define LED2_NODE DT_ALIAS(led2)
Definition at line 15 of file io.c.
LED3_NODE
#define LED3_NODE DT_ALIAS(led3)
Definition at line 16 of file io.c.
Function Documentation
button_pressed()
void button_pressed (const struct device * dev, struct gpio_callback * cb, uint32_t pins)
Definition at line 52 of file io.c.
 {
     if (cb == &btn_cb_data[0])
     {
         if (!setpoint_defined)
         {
             setpoint_defined = true;
             printk("\n[INFO] Desired temperature set to: %d ºC\n", temp_setpoint_buffer);
             printk("[SETUP] Use ▲ (Button 2) and ▼ (Button 4) to define maximum temperature.\n");
         }
         else if (!max_temp_defined)
         {
             max_temp_defined = true;
             rtdb_set_set_temp(temp_setpoint_buffer);
             rtdb_set_max_temp(temp_max_buffer);
             printk("\n[INFO] Maximum temperature set to: %d ºC\n", temp_max_buffer);
             printk("[INFO] System is now ready!\n");
             printk("[INFO] Press Button 1 to toggle ON/OFF.\n\n");
         }
         else
         {
             rtdb_toggle_system_state();
             io_set_led(0, rtdb_get_system_state());
         }
     }
     else if (cb == &btn_cb_data[1])
     {
         if (!setpoint_defined)
         {
             temp_setpoint_buffer++;
         }
         else if (!max_temp_defined)
         {
             temp_max_buffer++;
         }
         else
         {
             rtdb_increment_set_temp();
         }
         if (!setpoint_defined)
         {
             printk("\r[SETUP] Desired Temperature: %2d ºC   |   Maximum Temperature: ?? ºC\033[K", temp_setpoint_buffer);
         }
         else if (!max_temp_defined)
         {
             printk("\r[SETUP] Desired Temperature: %2d ºC   |   Maximum Temperature: %2d ºC\033[K", temp_setpoint_buffer, temp_max_buffer);
         }
         else
         {
             int t = rtdb_get_current_temp();
             int s = rtdb_get_set_temp();
             int m = rtdb_get_max_temp();
             printk("\n[INFO] Desired temperature set to: %d ºC\n", s);
             printk("Current Temperature: %2d ºC    |    Desired Temperature: %2d ºC    |    Maximum Temperature: %2d ºC\033[K", t, s, m);
         }
     }
     else if (cb == &btn_cb_data[3])
     {
         if (!setpoint_defined)
         {
             temp_setpoint_buffer--;
         }
         else if (!max_temp_defined)
         {
             temp_max_buffer--;
         }
         else
         {
             rtdb_decrement_set_temp();
         }
         if (!setpoint_defined)
         {
             printk("\r[SETUP] Desired Temperature: %2d ºC   |   Maximum Temperature: ?? ºC\033[K", temp_setpoint_buffer);
         }
         else if (!max_temp_defined)
         {
             printk("\r[SETUP] Desired Temperature: %2d ºC   |   Maximum Temperature: %2d ºC\033[K", temp_setpoint_buffer, temp_max_buffer);
         }
         else
         {
             int t = rtdb_get_current_temp();
             int s = rtdb_get_set_temp();
             int m = rtdb_get_max_temp();
             printk("\n[INFO] Desired temperature set to: %d ºC\n", s);
             printk("Current Temperature: %2d ºC    |    Desired Temperature: %2d ºC    |    Maximum Temperature: %2d ºC\033[K", t, s, m);
         }
     }
     else if (cb == &btn_cb_data[2])
     {
         if (!setpoint_defined || !max_temp_defined) return;
         uart_mode = !uart_mode;
         if (uart_mode)
         {
             printk("\n\n[UART MODE] ─ UART Command Interface ─────────────\n");
             printk("Command: ");
         }
         else
         {
             int t = rtdb_get_current_temp();
             int s = rtdb_get_set_temp();
             int m = rtdb_get_max_temp();
             printk("\n[INFO] UART mode closed. Returning to system view...\n");
             printk("Current Temperature: %2d ºC    |    Desired Temperature: %2d ºC    |    Maximum Temperature: %2d ºC\033[K", t, s, m);
         }
     }
 }
References btn_cb_data, io_set_led(), max_temp_defined, rtdb_decrement_set_temp(), rtdb_get_current_temp(), rtdb_get_max_temp(), rtdb_get_set_temp(), rtdb_get_system_state(), rtdb_increment_set_temp(), rtdb_set_max_temp(), rtdb_set_set_temp(), rtdb_toggle_system_state(), setpoint_defined, temp_max_buffer, temp_setpoint_buffer, and uart_mode.
Referenced by io_init().
io_blink_led()
void io_blink_led (int id)
Toggles the state of a specific LED.
Useful for blinking indication.
Parameters
id The ID/index of the LED (0 to 3).
Definition at line 45 of file io.c.
 {
     static bool state = false;
     gpio_pin_set_dt(&leds[id], state);
     state = !state;
 }
References leds.
Referenced by control_task().
io_init()
void io_init (void)
Initializes all LED and button GPIOs.
Configures each LED as output and each button as input with interrupt capabilities. Also registers callback functions for button events.
Definition at line 166 of file io.c.
 {
     for (int i = 0; i < 4; i++)
     {
         if (!device_is_ready(leds[i].port)) return;
         gpio_pin_configure_dt(&leds[i], GPIO_OUTPUT_INACTIVE);
     }
     for (int i = 0; i < 4; i++)
     {
         if (!device_is_ready(buttons[i].port)) return;
         gpio_pin_configure_dt(&buttons[i], GPIO_INPUT);
         gpio_pin_interrupt_configure_dt(&buttons[i], GPIO_INT_EDGE_TO_ACTIVE);
         gpio_init_callback(&btn_cb_data[i], button_pressed, BIT(buttons[i].pin));
         gpio_add_callback(buttons[i].port, &btn_cb_data[i]);
     }
 }
References btn_cb_data, button_pressed(), buttons, and leds.
Referenced by main().
io_set_led()
void io_set_led (int id, int state)
Sets the state of a specific LED.
Parameters
id The ID/index of the LED (0 to 3).
state The desired state: 1 (on) or 0 (off).
Definition at line 40 of file io.c.
 {
     gpio_pin_set_dt(&leds[id], state);
 }
References leds.
Referenced by button_pressed(), and control_task().
Variable Documentation
btn_cb_data
struct gpio_callback btn_cb_data[4] static
Definition at line 38 of file io.c.
Referenced by button_pressed(), and io_init().
buttons
const struct gpio_dt_spec buttons[] static
Initial value:
= {
    GPIO_DT_SPEC_GET(BTN0_NODE, gpios),
    GPIO_DT_SPEC_GET(BTN1_NODE, gpios),
    GPIO_DT_SPEC_GET(BTN2_NODE, gpios),
    GPIO_DT_SPEC_GET(BTN3_NODE, gpios),
}
Definition at line 25 of file io.c.
Referenced by io_init().
leds
const struct gpio_dt_spec leds[] static
Initial value:
= {
    GPIO_DT_SPEC_GET(LED0_NODE, gpios),
    GPIO_DT_SPEC_GET(LED1_NODE, gpios),
    GPIO_DT_SPEC_GET(LED2_NODE, gpios),
    GPIO_DT_SPEC_GET(LED3_NODE, gpios),
}
Definition at line 18 of file io.c.
Referenced by io_blink_led(), io_init(), and io_set_led().
max_temp_defined
bool max_temp_defined
Definition at line 9 of file main.c.
Referenced by button_pressed(), and temperature_task().
setpoint_defined
bool setpoint_defined
Definition at line 8 of file main.c.
Referenced by button_pressed(), and temperature_task().
temp_max_buffer
int temp_max_buffer
Definition at line 13 of file main.c.
Referenced by button_pressed().
temp_setpoint_buffer
int temp_setpoint_buffer
Definition at line 12 of file main.c.
Referenced by button_pressed(), and main().
uart_mode
bool uart_mode
Definition at line 10 of file main.c.
Referenced by button_pressed(), and control_task().