SETR - Assignment 3: io.h File Reference
io.h File Reference
GPIO interface for LED control and button handling in the Smart Home Heater project.
Functions
void io_init (void)
Initializes all LED and button GPIOs.
void io_set_led (int id, int state)
Sets the state of a specific LED.
void io_blink_led (int id)
Toggles the state of a specific LED.
Detailed Description
GPIO interface for LED control and button handling in the Smart Home Heater project.
This module provides functions for initializing and controlling GPIO-connected LEDs and buttons. It supports system interaction via physical buttons and visual status indication through LEDs.
Authors
Duarte Caldeira, Tiago Saraiva
Definition in file io.h.
Function Documentation
io_blink_led()
void io_blink_led (int id)
Toggles the state of a specific LED.
Useful for blinking indication.
Parameters
id The ID/index of the LED (0 to 3).
Definition at line 45 of file io.c.
 {
     static bool state = false;
     gpio_pin_set_dt(&leds[id], state);
     state = !state;
 }
References leds.
Referenced by control_task().
io_init()
void io_init (void)
Initializes all LED and button GPIOs.
Configures each LED as output and each button as input with interrupt capabilities. Also registers callback functions for button events.
Definition at line 166 of file io.c.
 {
     for (int i = 0; i < 4; i++)
     {
         if (!device_is_ready(leds[i].port)) return;
         gpio_pin_configure_dt(&leds[i], GPIO_OUTPUT_INACTIVE);
     }
     for (int i = 0; i < 4; i++)
     {
         if (!device_is_ready(buttons[i].port)) return;
         gpio_pin_configure_dt(&buttons[i], GPIO_INPUT);
         gpio_pin_interrupt_configure_dt(&buttons[i], GPIO_INT_EDGE_TO_ACTIVE);
         gpio_init_callback(&btn_cb_data[i], button_pressed, BIT(buttons[i].pin));
         gpio_add_callback(buttons[i].port, &btn_cb_data[i]);
     }
 }
References btn_cb_data, button_pressed(), buttons, and leds.
Referenced by main().
io_set_led()
void io_set_led (int id, int state)
Sets the state of a specific LED.
Parameters
id The ID/index of the LED (0 to 3).
state The desired state: 1 (on) or 0 (off).
Definition at line 40 of file io.c.
 {
     gpio_pin_set_dt(&leds[id], state);
 }
References leds.
Referenced by button_pressed(), and control_task().