SETR - Assignment 3: main.c File Reference
main.c File Reference
#include <zephyr/kernel.h>
#include "io.h"
#include "uart.h"
#include "rtdb.h"
#include "pwm.h"
#include "sensor_i2c.h"
Macros
#define TEMP_UPDATE_INTERVAL_MS 1000
#define CONTROL_INTERVAL_MS 500
Functions
void temperature_task (void)
void control_task (void)
K_THREAD_DEFINE (temp_id, 1024, temperature_task, NULL, NULL, NULL, 5, 0, 0)
K_THREAD_DEFINE (ctrl_id, 1024, control_task, NULL, NULL, NULL, 5, 0, 0)
void main (void)
Variables
bool setpoint_defined = false
bool max_temp_defined = false
bool uart_mode = false
int temp_setpoint_buffer = 25
int temp_max_buffer = 40
Macro Definition Documentation
CONTROL_INTERVAL_MS
#define CONTROL_INTERVAL_MS 500
Definition at line 16 of file main.c.
TEMP_UPDATE_INTERVAL_MS
#define TEMP_UPDATE_INTERVAL_MS 1000
Definition at line 15 of file main.c.
Function Documentation
control_task()
void control_task (void)
Definition at line 35 of file main.c.
 {
     int last_temp = -1000;
     int last_set = -1000;
     float integral = 0.0f;
     float previous_error = 0.0f;
     float Kp, Ki, Kd;
     rtdb_get_pid_params(&Kp, &Ki, &Kd);
     while (1)
     {
         if (!rtdb_get_system_state())
         {
             io_set_led(0, 0);
             io_set_led(1, 0);
             io_set_led(2, 0);
             io_set_led(3, 0);
             pwm_set_dc(0);
             last_temp = -1000;
             last_set = -1000;
             integral = 0;
             previous_error = 0;
             k_msleep(CONTROL_INTERVAL_MS);
             continue;
         }
         int t = rtdb_get_current_temp();
         int s = rtdb_get_set_temp();
         int m = rtdb_get_max_temp();
         if ((t != last_temp || s != last_set) && !uart_mode)
         {
             int m = rtdb_get_max_temp();
             printk("\rCurrent Temperature: %2d ºC    |    Desired Temperature: %2d ºC    |    Maximum Temperature: %2d ºC\033[K", t, s, m);
             last_temp = t;
             last_set = s;
         }
         //if (t >= m) {
         //    pwm_ctrl_set_duty_cycle_percent(0);
         //    k_msleep(CONTROL_INTERVAL_MS);
         //    continue;
         //}
         float error = (float)(s - t);
         integral += error * (CONTROL_INTERVAL_MS / 1000.0f);
         float derivative = (error - previous_error) / (CONTROL_INTERVAL_MS / 1000.0f);
         float output = Kp * error + Ki * integral + Kd * derivative;
         if (output < 0) output = 0;
         if (output > 100) output = 100;
         pwm_set_dc(100 - (int)output);
         if (error > 2)
         {
             io_set_led(1, 0);
             io_blink_led(2); // heating
             io_set_led(3, 0);
         }
         else if (error < -2)
         {
             io_set_led(1, 0);
             io_set_led(2, 0);
             io_blink_led(3); // cooling
         }
         else
         {
             io_set_led(1, 1); // stable
             io_set_led(2, 0);
             io_set_led(3, 0);
         }
         k_msleep(CONTROL_INTERVAL_MS);
     }
 }
References CONTROL_INTERVAL_MS, io_blink_led(), io_set_led(), Kd, Ki, Kp, pwm_set_dc(), rtdb_get_current_temp(), rtdb_get_max_temp(), rtdb_get_pid_params(), rtdb_get_set_temp(), rtdb_get_system_state(), and uart_mode.
K_THREAD_DEFINE() [1/2]
K_THREAD_DEFINE (ctrl_id , 1024 , control_task , NULL , NULL , NULL , 5 , 0 , 0)
K_THREAD_DEFINE() [2/2]
K_THREAD_DEFINE (temp_id , 1024 , temperature_task , NULL , NULL , NULL , 5 , 0 , 0)
main()
void main (void)
Definition at line 118 of file main.c.
 {
     printk("Boot start\n");
     io_init();
     uart_init();
     rtdb_init();
     pwm_init();
     printk("\033[2J\033[H");
     printk("╔════════════════════════════════════╗\n");
     printk("║        SMART HOME HEATER           ║\n");
     printk("╚════════════════════════════════════╝\n\n");
     printk("[SETUP] Use ▲ (Button 2) and ▼ (Button 4) to define setpoint.\n");
     printk("[INFO] Press Button 1 to confirm setpoint.\n\n");
     printk("\r\033[2K[SETUP] Desired Temperature: %2d ºC  |  Maximum Temperature: ?? ºC", temp_setpoint_buffer);
 }
References io_init(), pwm_init(), rtdb_init(), temp_setpoint_buffer, and uart_init().
temperature_task()
void temperature_task (void)
Definition at line 18 of file main.c.
 {
     while (1) {
         if (!setpoint_defined || !max_temp_defined || !rtdb_get_system_state()) {
             k_msleep(500);
             continue;
         }
         int temp = sensor_init_read();
         if (temp >= 0) {
             rtdb_set_current_temp(temp);
         }
         k_msleep(TEMP_UPDATE_INTERVAL_MS);
     }
 }
References max_temp_defined, rtdb_get_system_state(), rtdb_set_current_temp(), sensor_init_read(), setpoint_defined, and TEMP_UPDATE_INTERVAL_MS.
Variable Documentation
max_temp_defined
bool max_temp_defined = false
Definition at line 9 of file main.c.
Referenced by button_pressed(), and temperature_task().
setpoint_defined
bool setpoint_defined = false
Definition at line 8 of file main.c.
Referenced by button_pressed(), and temperature_task().
temp_max_buffer
int temp_max_buffer = 40
Definition at line 13 of file main.c.
Referenced by button_pressed().
temp_setpoint_buffer
int temp_setpoint_buffer = 25
Definition at line 12 of file main.c.
Referenced by button_pressed(), and main().
uart_mode
bool uart_mode = false
Definition at line 10 of file main.c.
Referenced by button_pressed(), and control_task().