SETR - Assignment 3: pwm.c File Reference
pwm.c File Reference
#include "pwm.h"
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/sys/printk.h>
Macros
#define PWM_NODE DT_NODELABEL(pwm_led2)
Functions
int pwm_init (void)
Initializes the PWM hardware.
int pwm_set_dc (uint8_t percent)
Sets the PWM duty cycle.
Variables
static const struct pwm_dt_spec pwm_led = PWM_DT_SPEC_GET(PWM_NODE)
Macro Definition Documentation
PWM_NODE
#define PWM_NODE DT_NODELABEL(pwm_led2)
Definition at line 6 of file pwm.c.
Function Documentation
pwm_init()
int pwm_init (void)
Initializes the PWM hardware.
Returns
0 on success, negative value on failure.
Definition at line 9 of file pwm.c.
 {
     if (!device_is_ready(pwm_led.dev)) {
         printk("PWM device not ready!\n");
         return -1;
     }
     return pwm_set_dc(0);
 }
References pwm_led, and pwm_set_dc().
Referenced by main().
pwm_set_dc()
int pwm_set_dc (uint8_t percent)
Sets the PWM duty cycle.
Parameters
percent Duty cycle as a percentage (0 to 100).
Returns
0 on success, negative value on error.
Definition at line 19 of file pwm.c.
 {
     if (percent > 100) percent = 100;
     uint32_t pulse = (PWM_PERIOD_NS * percent) / 100;
     return pwm_set_dt(&pwm_led, PWM_PERIOD_NS, pulse);
 }
References pwm_led, and PWM_PERIOD_NS.
Referenced by control_task(), and pwm_init().
Variable Documentation
pwm_led
const struct pwm_dt_spec pwm_led = PWM_DT_SPEC_GET(PWM_NODE) static
Definition at line 7 of file pwm.c.
Referenced by pwm_init(), and pwm_set_dc().