SETR - Assignment 3: pwm.h File Reference
pwm.h File Reference
PWM control interface for Smart Home Heater.
#include <zephyr/drivers/pwm.h>
Macros
#define PWM_FREQ_HZ 100
PWM frequency in Hz.
#define PWM_PERIOD_NS (1000000000UL / PWM_FREQ_HZ)
PWM period in nanoseconds.
Functions
int pwm_init (void)
Initializes the PWM hardware.
int pwm_set_dc (uint8_t percent)
Sets the PWM duty cycle.
Detailed Description
PWM control interface for Smart Home Heater.
Provides functions to initialize and configure PWM output to control a heating element or fan with duty cycle.
Authors
Duarte Caldeira, Tiago Saraiva
Definition in file pwm.h.
Macro Definition Documentation
PWM_FREQ_HZ
#define PWM_FREQ_HZ 100
PWM frequency in Hz.
Definition at line 17 of file pwm.h.
PWM_PERIOD_NS
#define PWM_PERIOD_NS (1000000000UL / PWM_FREQ_HZ)
PWM period in nanoseconds.
Definition at line 18 of file pwm.h.
Function Documentation
pwm_init()
int pwm_init (void)
Initializes the PWM hardware.
Returns
0 on success, negative value on failure.
Definition at line 9 of file pwm.c.
 {
     if (!device_is_ready(pwm_led.dev)) {
         printk("PWM device not ready!\n");
         return -1;
     }
     return pwm_set_dc(0);
 }
References pwm_led, and pwm_set_dc().
Referenced by main().
pwm_set_dc()
int pwm_set_dc (uint8_t percent)
Sets the PWM duty cycle.
Parameters
percent Duty cycle as a percentage (0 to 100).
Returns
0 on success, negative value on error.
Definition at line 19 of file pwm.c.
 {
     if (percent > 100) percent = 100;
     uint32_t pulse = (PWM_PERIOD_NS * percent) / 100;
     return pwm_set_dt(&pwm_led, PWM_PERIOD_NS, pulse);
 }
References pwm_led, and PWM_PERIOD_NS.
Referenced by control_task(), and pwm_init().