SETR - Assignment 3: rtdb.h File Reference
rtdb.h File Reference
Real-Time Database.
Functions
void rtdb_init (void)
Initializes the RTDB module.
void rtdb_set_current_temp (int temp)
Sets the current measured temperature.
int rtdb_get_current_temp (void)
Gets the current measured temperature.
void rtdb_set_set_temp (int temp)
Sets the desired setpoint temperature.
int rtdb_get_set_temp (void)
Gets the desired setpoint temperature.
void rtdb_increment_set_temp (void)
Increments the desired setpoint temperature.
void rtdb_decrement_set_temp (void)
Decrements the desired setpoint temperature.
void rtdb_set_max_temp (int max)
Sets the maximum allowed temperature.
int rtdb_get_max_temp (void)
Gets the maximum allowed temperature.
void rtdb_toggle_system_state (void)
Toggles the current system ON/OFF state.
int rtdb_get_system_state (void)
Gets the current system ON/OFF state.
void rtdb_set_pid_params (float kp, float ki, float kd)
Sets the PID control parameters.
void rtdb_get_pid_params (float *kp, float *ki, float *kd)
Gets the PID control parameters.
Detailed Description
Real-Time Database.
This module stores system state including current temperature, desired setpoint, maximum limit, and PID parameters. Thread-safe access is ensured via mutexes.
Authors
Duarte Caldeira, Tiago Saraiva
Definition in file rtdb.h.
Function Documentation
rtdb_decrement_set_temp()
void rtdb_decrement_set_temp (void)
Decrements the desired setpoint temperature.
Definition at line 63 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     if (set_temp > 0) set_temp--;
     k_mutex_unlock(&rtdb_mutex);
 }
References set_temp.
Referenced by button_pressed().
rtdb_get_current_temp()
int rtdb_get_current_temp (void)
Gets the current measured temperature.
Returns
Current temperature in degrees Celsius.
Definition at line 24 of file rtdb.c.
 {
     int temp;
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     temp = current_temp;
     k_mutex_unlock(&rtdb_mutex);
     return temp;
 }
References current_temp.
Referenced by button_pressed(), cmd_process(), and control_task().
rtdb_get_max_temp()
int rtdb_get_max_temp (void)
Gets the maximum allowed temperature.
Returns
Maximum temperature in degrees Celsius.
Definition at line 84 of file rtdb.c.
 {
     int max;
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     max = max_temp;
     k_mutex_unlock(&rtdb_mutex);
     return max;
 }
References max_temp.
Referenced by button_pressed(), and control_task().
rtdb_get_pid_params()
void rtdb_get_pid_params (float * kp, float * ki, float * kd)
Gets the PID control parameters.
Parameters
kp Pointer to store proportional gain.
ki Pointer to store integral gain.
kd Pointer to store derivative gain.
Definition at line 115 of file rtdb.c.
{
     if (p) *p = Kp;
     if (i) *i = Ki;
     if (d) *d = Kd;
 }
References Kd, Ki, and Kp.
Referenced by control_task().
rtdb_get_set_temp()
int rtdb_get_set_temp (void)
Gets the desired setpoint temperature.
Returns
Desired temperature in degrees Celsius.
Definition at line 47 of file rtdb.c.
 {
     int temp;
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     temp = set_temp;
     k_mutex_unlock(&rtdb_mutex);
     return temp;
 }
References set_temp.
Referenced by button_pressed(), and control_task().
rtdb_get_system_state()
int rtdb_get_system_state (void)
Gets the current system ON/OFF state.
Returns
1 if ON, 0 if OFF.
Definition at line 93 of file rtdb.c.
 {
     int state;
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     state = system_on;
     k_mutex_unlock(&rtdb_mutex);
     return state;
 }
References system_on.
Referenced by button_pressed(), control_task(), and temperature_task().
rtdb_increment_set_temp()
void rtdb_increment_set_temp (void)
Increments the desired setpoint temperature.
Definition at line 56 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     if (set_temp < max_temp) set_temp++;
     k_mutex_unlock(&rtdb_mutex);
 }
References max_temp, and set_temp.
Referenced by button_pressed().
rtdb_init()
void rtdb_init (void)
Initializes the RTDB module.
Definition at line 15 of file rtdb.c.
 {}
Referenced by main().
rtdb_set_current_temp()
void rtdb_set_current_temp (int temp)
Sets the current measured temperature.
Parameters
temp The current temperature in degrees Celsius.
Definition at line 17 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     current_temp = temp;
     k_mutex_unlock(&rtdb_mutex);
 }
References current_temp.
Referenced by temperature_task().
rtdb_set_max_temp()
void rtdb_set_max_temp (int max)
Sets the maximum allowed temperature.
Parameters
max Maximum temperature in degrees Celsius.
Definition at line 77 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     max_temp = max;
     k_mutex_unlock(&rtdb_mutex);
 }
References max_temp.
Referenced by button_pressed(), and cmd_process().
rtdb_set_pid_params()
void rtdb_set_pid_params (float kp, float ki, float kd)
Sets the PID control parameters.
Parameters
kp Proportional gain.
ki Integral gain.
kd Derivative gain.
Definition at line 109 of file rtdb.c.
{
     Kp = p;
     Ki = i;
     Kd = d;
 }
References Kd, Ki, and Kp.
Referenced by cmd_process().
rtdb_set_set_temp()
void rtdb_set_set_temp (int temp)
Sets the desired setpoint temperature.
Parameters
temp The desired temperature in degrees Celsius.
Definition at line 70 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     set_temp = temp;
     k_mutex_unlock(&rtdb_mutex);
 }
References set_temp.
Referenced by button_pressed().
rtdb_toggle_system_state()
void rtdb_toggle_system_state (void)
Toggles the current system ON/OFF state.
Definition at line 102 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     system_on = !system_on;
     k_mutex_unlock(&rtdb_mutex);
 }
References system_on.
Referenced by button_pressed().