SETR - Assignment 3: rtdb.c File Reference
rtdb.c File Reference
#include <zephyr/kernel.h>
#include "rtdb.h"
Functions
K_MUTEX_DEFINE (rtdb_mutex)
void rtdb_init (void)
Initializes the RTDB module.
void rtdb_set_current_temp (int temp)
Sets the current measured temperature.
int rtdb_get_current_temp (void)
Gets the current measured temperature.
int rtdb_get_set_temp (void)
Gets the desired setpoint temperature.
void rtdb_increment_set_temp (void)
Increments the desired setpoint temperature.
void rtdb_decrement_set_temp (void)
Decrements the desired setpoint temperature.
void rtdb_set_set_temp (int temp)
Sets the desired setpoint temperature.
void rtdb_set_max_temp (int max)
Sets the maximum allowed temperature.
int rtdb_get_max_temp (void)
Gets the maximum allowed temperature.
int rtdb_get_system_state (void)
Gets the current system ON/OFF state.
void rtdb_toggle_system_state (void)
Toggles the current system ON/OFF state.
void rtdb_set_pid_params (float p, float i, float d)
Sets the PID control parameters.
void rtdb_get_pid_params (float *p, float *i, float *d)
Gets the PID control parameters.
Variables
static int current_temp = 0
static int set_temp = 25
static int max_temp = 50
static bool system_on = false
static float Kp = 2.0f
static float Ki = 0.1f
static float Kd = 1.0f
Function Documentation
K_MUTEX_DEFINE()
K_MUTEX_DEFINE (rtdb_mutex)
rtdb_decrement_set_temp()
void rtdb_decrement_set_temp (void)
Decrements the desired setpoint temperature.
Definition at line 63 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     if (set_temp > 0) set_temp--;
     k_mutex_unlock(&rtdb_mutex);
 }
References set_temp.
Referenced by button_pressed().
rtdb_get_current_temp()
int rtdb_get_current_temp (void)
Gets the current measured temperature.
Returns
Current temperature in degrees Celsius.
Definition at line 24 of file rtdb.c.
 {
     int temp;
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     temp = current_temp;
     k_mutex_unlock(&rtdb_mutex);
     return temp;
 }
References current_temp.
Referenced by button_pressed(), cmd_process(), and control_task().
rtdb_get_max_temp()
int rtdb_get_max_temp (void)
Gets the maximum allowed temperature.
Returns
Maximum temperature in degrees Celsius.
Definition at line 84 of file rtdb.c.
 {
     int max;
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     max = max_temp;
     k_mutex_unlock(&rtdb_mutex);
     return max;
 }
References max_temp.
Referenced by button_pressed(), and control_task().
rtdb_get_pid_params()
void rtdb_get_pid_params (float * kp, float * ki, float * kd)
Gets the PID control parameters.
Parameters
kp Pointer to store proportional gain.
ki Pointer to store integral gain.
kd Pointer to store derivative gain.
Definition at line 115 of file rtdb.c.
{
     if (p) *p = Kp;
     if (i) *i = Ki;
     if (d) *d = Kd;
 }
References Kd, Ki, and Kp.
Referenced by control_task().
rtdb_get_set_temp()
int rtdb_get_set_temp (void)
Gets the desired setpoint temperature.
Returns
Desired temperature in degrees Celsius.
Definition at line 47 of file rtdb.c.
 {
     int temp;
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     temp = set_temp;
     k_mutex_unlock(&rtdb_mutex);
     return temp;
 }
References set_temp.
Referenced by button_pressed(), and control_task().
rtdb_get_system_state()
int rtdb_get_system_state (void)
Gets the current system ON/OFF state.
Returns
1 if ON, 0 if OFF.
Definition at line 93 of file rtdb.c.
 {
     int state;
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     state = system_on;
     k_mutex_unlock(&rtdb_mutex);
     return state;
 }
References system_on.
Referenced by button_pressed(), control_task(), and temperature_task().
rtdb_increment_set_temp()
void rtdb_increment_set_temp (void)
Increments the desired setpoint temperature.
Definition at line 56 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     if (set_temp < max_temp) set_temp++;
     k_mutex_unlock(&rtdb_mutex);
 }
References max_temp, and set_temp.
Referenced by button_pressed().
rtdb_init()
void rtdb_init (void)
Initializes the RTDB module.
Definition at line 15 of file rtdb.c.
 {}
Referenced by main().
rtdb_set_current_temp()
void rtdb_set_current_temp (int temp)
Sets the current measured temperature.
Parameters
temp The current temperature in degrees Celsius.
Definition at line 17 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     current_temp = temp;
     k_mutex_unlock(&rtdb_mutex);
 }
References current_temp.
Referenced by temperature_task().
rtdb_set_max_temp()
void rtdb_set_max_temp (int max)
Sets the maximum allowed temperature.
Parameters
max Maximum temperature in degrees Celsius.
Definition at line 77 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     max_temp = max;
     k_mutex_unlock(&rtdb_mutex);
 }
References max_temp.
Referenced by button_pressed(), and cmd_process().
rtdb_set_pid_params()
void rtdb_set_pid_params (float kp, float ki, float kd)
Sets the PID control parameters.
Parameters
kp Proportional gain.
ki Integral gain.
kd Derivative gain.
Definition at line 109 of file rtdb.c.
{
     Kp = p;
     Ki = i;
     Kd = d;
 }
References Kd, Ki, and Kp.
Referenced by cmd_process().
rtdb_set_set_temp()
void rtdb_set_set_temp (int temp)
Sets the desired setpoint temperature.
Parameters
temp The desired temperature in degrees Celsius.
Definition at line 70 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     set_temp = temp;
     k_mutex_unlock(&rtdb_mutex);
 }
References set_temp.
Referenced by button_pressed().
rtdb_toggle_system_state()
void rtdb_toggle_system_state (void)
Toggles the current system ON/OFF state.
Definition at line 102 of file rtdb.c.
 {
     k_mutex_lock(&rtdb_mutex, K_FOREVER);
     system_on = !system_on;
     k_mutex_unlock(&rtdb_mutex);
 }
References system_on.
Referenced by button_pressed().
Variable Documentation
current_temp
int current_temp = 0 static
Definition at line 4 of file rtdb.c.
Referenced by rtdb_get_current_temp(), and rtdb_set_current_temp().
Kd
float Kd = 1.0f static
Definition at line 11 of file rtdb.c.
Referenced by control_task(), rtdb_get_pid_params(), and rtdb_set_pid_params().
Ki
float Ki = 0.1f static
Definition at line 10 of file rtdb.c.
Referenced by control_task(), rtdb_get_pid_params(), and rtdb_set_pid_params().
Kp
float Kp = 2.0f static
Definition at line 9 of file rtdb.c.
Referenced by control_task(), rtdb_get_pid_params(), and rtdb_set_pid_params().
max_temp
int max_temp = 50 static
Definition at line 6 of file rtdb.c.
Referenced by rtdb_get_max_temp(), rtdb_increment_set_temp(), and rtdb_set_max_temp().
set_temp
int set_temp = 25 static
Definition at line 5 of file rtdb.c.
Referenced by rtdb_decrement_set_temp(), rtdb_get_set_temp(), rtdb_increment_set_temp(), and rtdb_set_set_temp().
system_on
bool system_on = false static
Definition at line 7 of file rtdb.c.
Referenced by rtdb_get_system_state(), and rtdb_toggle_system_state().