SETR - Assignment 3: uart.c File Reference
uart.c File Reference
#include <zephyr/kernel.h>
#include <zephyr/drivers/uart.h>
#include <zephyr/device.h>
#include <zephyr/sys/printk.h>
#include <string.h>
#include "uart.h"
#include "cmdproc.h"
Macros
#define UART_NODE DT_NODELABEL(uart0)
#define RXBUF_SIZE 64
#define RX_TIMEOUT_US 1000
Functions
static void uart_cb (const struct device *dev, struct uart_event *evt, void *user_data)
void uart_init (void)
Initializes UART and sets up RX callback.
void uart_send_string (const char *msg)
Sends a null-terminated string over UART.
void uart_send_bytes (const uint8_t *buf, int len)
Sends bytes over UART.
Variables
const struct device * uart_dev = DEVICE_DT_GET(UART_NODE)
static uint8_t rx_buf [RXBUF_SIZE]
static uint8_t rx_data [RXBUF_SIZE]
static volatile int rx_len = 0
Macro Definition Documentation
RX_TIMEOUT_US
#define RX_TIMEOUT_US 1000
Definition at line 11 of file uart.c.
RXBUF_SIZE
#define RXBUF_SIZE 64
Definition at line 10 of file uart.c.
UART_NODE
#define UART_NODE DT_NODELABEL(uart0)
Definition at line 9 of file uart.c.
Function Documentation
uart_cb()
static void uart_cb (const struct device * dev, struct uart_event * evt, void * user_data) static
Definition at line 18 of file uart.c.
 {
     switch (evt->type) {
     case UART_RX_RDY: {
         for (int i = 0; i < evt->data.rx.len; i++) {
             char c = rx_buf[evt->data.rx.offset + i];
             if (c == '#') {
                 rx_len = 0;  // início da frame
             }
             if (rx_len < RXBUF_SIZE - 1) {
                 rx_data[rx_len++] = c;
             }
             if (c == '!') {
                 rx_data[rx_len] = '\0';  // termina string
                 //printk("\nCommand UART: %s\n", rx_data);
                 cmd_process(rx_data, rx_len);
                 rx_len = 0;
                 memset(rx_data, 0, sizeof(rx_data));
                 //printk("\nCommand UART: %s\n", rx_data);
             }
         }
         break;
     }
     case UART_RX_DISABLED:
         uart_rx_enable(uart_dev, rx_buf, sizeof(rx_buf), RX_TIMEOUT_US);
         break;
     default:
         break;
     }
 }
References cmd_process(), rx_buf, rx_data, rx_len, RX_TIMEOUT_US, RXBUF_SIZE, and uart_dev.
Referenced by uart_init().
uart_init()
void uart_init (void)
Initializes UART and sets up RX callback.
Definition at line 55 of file uart.c.
 {
     if (!device_is_ready(uart_dev)) {
         printk("UART device not ready\n");
         return;
     }
     if (uart_callback_set(uart_dev, uart_cb, NULL) != 0) {
         printk("Failed to set UART callback\n");
         return;
     }
     if (uart_rx_enable(uart_dev, rx_buf, sizeof(rx_buf), RX_TIMEOUT_US) != 0) {
         printk("Failed to enable UART RX\n");
         return;
     }
     printk("UART initialized\n");
 }
References rx_buf, RX_TIMEOUT_US, uart_cb(), and uart_dev.
Referenced by main().
uart_send_bytes()
void uart_send_bytes (const uint8_t * buf, int len)
Sends bytes over UART.
Parameters
buf Pointer to the buffer.
len Number of bytes to send.
Definition at line 80 of file uart.c.
 {
     uart_tx(uart_dev, buf, len, SYS_FOREVER_MS);
 }
References uart_dev.
uart_send_string()
void uart_send_string (const char * msg)
Sends a null-terminated string over UART.
Parameters
msg Pointer to the string to send.
Definition at line 75 of file uart.c.
 {
     uart_tx(uart_dev, msg, strlen(msg), SYS_FOREVER_MS);
 }
References uart_dev.
Referenced by send_response().
Variable Documentation
rx_buf
uint8_t rx_buf[RXBUF_SIZE] static
Definition at line 14 of file uart.c.
Referenced by uart_cb(), and uart_init().
rx_data
uint8_t rx_data[RXBUF_SIZE] static
Definition at line 15 of file uart.c.
Referenced by uart_cb().
rx_len
volatile int rx_len = 0 static
Definition at line 16 of file uart.c.
Referenced by uart_cb().
uart_dev
const struct device* uart_dev = DEVICE_DT_GET(UART_NODE)
Definition at line 13 of file uart.c.
Referenced by uart_cb(), uart_init(), uart_send_bytes(), and uart_send_string().