SETR - Assignment 3: uart.h File Reference
uart.h File Reference
UART communication interface for Smart Home Heater.
Functions
void uart_init (void)
Initializes UART and sets up RX callback.
void uart_send_string (const char *msg)
Sends a null-terminated string over UART.
void uart_send_bytes (const uint8_t *buf, int len)
Sends bytes over UART.
Detailed Description
UART communication interface for Smart Home Heater.
This module enables UART communication with external devices. It supports sending commands and receiving frames using UART0.
Authors
Duarte Caldeira, Tiago Saraiva
Definition in file uart.h.
Function Documentation
uart_init()
void uart_init (void)
Initializes UART and sets up RX callback.
Definition at line 55 of file uart.c.
 {
     if (!device_is_ready(uart_dev)) {
         printk("UART device not ready\n");
         return;
     }
     if (uart_callback_set(uart_dev, uart_cb, NULL) != 0) {
         printk("Failed to set UART callback\n");
         return;
     }
     if (uart_rx_enable(uart_dev, rx_buf, sizeof(rx_buf), RX_TIMEOUT_US) != 0) {
         printk("Failed to enable UART RX\n");
         return;
     }
     printk("UART initialized\n");
 }
References rx_buf, RX_TIMEOUT_US, uart_cb(), and uart_dev.
Referenced by main().
uart_send_bytes()
void uart_send_bytes (const uint8_t * buf, int len)
Sends bytes over UART.
Parameters
buf Pointer to the buffer.
len Number of bytes to send.
Definition at line 80 of file uart.c.
 {
     uart_tx(uart_dev, buf, len, SYS_FOREVER_MS);
 }
References uart_dev.
uart_send_string()
void uart_send_string (const char * msg)
Sends a null-terminated string over UART.
Parameters
msg Pointer to the string to send.
Definition at line 75 of file uart.c.
 {
     uart_tx(uart_dev, msg, strlen(msg), SYS_FOREVER_MS);
 }
References uart_dev.
Referenced by send_response().